import Foundation

struct CaptionCue: Identifiable, Hashable {
    let id: Int
    let start: TimeInterval
    let end: TimeInterval
    let text: String

    func contains(_ time: TimeInterval) -> Bool {
        time >= start && time < end
    }
}

struct CaptionResult: Hashable {
    let languageCode: String
    let displayName: String
    let isAutoGenerated: Bool
    let isTranslated: Bool
    let cues: [CaptionCue]
}

enum CaptionServiceError: LocalizedError {
    case invalidVideoID
    case invalidResponse
    case captionDataNotFound
    case invalidCaptionURL
    case invalidCaptionPayload

    var errorDescription: String? {
        switch self {
        case .invalidVideoID:
            return "Neplatné video ID pro titulky."
        case .invalidResponse:
            return "YouTube nevrátil platnou odpověď pro titulky."
        case .captionDataNotFound:
            return "Video nemá dostupné titulky."
        case .invalidCaptionURL:
            return "Nepodařilo se sestavit adresu titulků."
        case .invalidCaptionPayload:
            return "YouTube vrátil titulky v neznámém formátu."
        }
    }
}

actor CaptionService {
    static let shared = CaptionService()

    func preferredCaptions(
        videoID: String,
        preferredLanguage: String = "cs",
        allowTranslation: Bool = true
    ) async throws -> CaptionResult? {
        guard videoID.count == 11 else {
            throw CaptionServiceError.invalidVideoID
        }

        let watchURL = URL(
            string: "https://www.youtube.com/watch?v=\(videoID)&hl=cs&gl=CZ"
        )!

        var request = URLRequest(url: watchURL)
        request.timeoutInterval = 20
        Self.applyYouTubeHeaders(to: &request)

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let http = response as? HTTPURLResponse,
              (200..<300).contains(http.statusCode),
              let html = String(data: data, encoding: .utf8) else {
            throw CaptionServiceError.invalidResponse
        }

        guard let playerData = Self.extractPlayerResponse(from: html),
              let root = try? JSONSerialization.jsonObject(with: playerData) as? [String: Any],
              let captions = root["captions"] as? [String: Any],
              let renderer = captions["playerCaptionsTracklistRenderer"] as? [String: Any],
              let tracks = renderer["captionTracks"] as? [[String: Any]],
              !tracks.isEmpty else {
            return nil
        }

        let translationLanguages = Set(
            (renderer["translationLanguages"] as? [[String: Any]] ?? [])
                .compactMap { $0["languageCode"] as? String }
        )

        let nativeTrack = tracks
            .filter { ($0["languageCode"] as? String) == preferredLanguage }
            .sorted {
                Self.isAutoGenerated(track: $0) == false
                    && Self.isAutoGenerated(track: $1) == true
            }
            .first

        if let nativeTrack {
            return try await loadTrack(
                nativeTrack,
                outputLanguage: preferredLanguage,
                translated: false
            )
        }

        guard allowTranslation,
              translationLanguages.contains(preferredLanguage) else {
            return nil
        }

        let translatable = tracks
            .filter { ($0["isTranslatable"] as? Bool) == true }
            .sorted {
                Self.isAutoGenerated(track: $0) == false
                    && Self.isAutoGenerated(track: $1) == true
            }
            .first

        guard let translatable else {
            return nil
        }

        return try await loadTrack(
            translatable,
            outputLanguage: preferredLanguage,
            translated: true
        )
    }

    private func loadTrack(
        _ track: [String: Any],
        outputLanguage: String,
        translated: Bool
    ) async throws -> CaptionResult {
        guard let rawURL = track["baseUrl"] as? String,
              var components = URLComponents(string: rawURL) else {
            throw CaptionServiceError.invalidCaptionURL
        }

        var query = components.queryItems ?? []
        query.removeAll { $0.name == "fmt" || $0.name == "tlang" }
        query.append(URLQueryItem(name: "fmt", value: "json3"))

        if translated {
            query.append(URLQueryItem(name: "tlang", value: outputLanguage))
        }

        components.queryItems = query

        guard let url = components.url else {
            throw CaptionServiceError.invalidCaptionURL
        }

        var request = URLRequest(url: url)
        request.timeoutInterval = 20
        Self.applyYouTubeHeaders(to: &request)

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let http = response as? HTTPURLResponse,
              (200..<300).contains(http.statusCode),
              !data.isEmpty else {
            throw CaptionServiceError.invalidResponse
        }

        let cues = try Self.parseJSON3(data)

        guard !cues.isEmpty else {
            throw CaptionServiceError.invalidCaptionPayload
        }

        let originalName = Self.text(from: track["name"])
            ?? (track["languageCode"] as? String)
            ?? "Titulky"

        return CaptionResult(
            languageCode: outputLanguage,
            displayName: translated
                ? "Čeština – automatický překlad"
                : originalName,
            isAutoGenerated: Self.isAutoGenerated(track: track),
            isTranslated: translated,
            cues: cues
        )
    }

    private static func parseJSON3(_ data: Data) throws -> [CaptionCue] {
        guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let events = root["events"] as? [[String: Any]] else {
            throw CaptionServiceError.invalidCaptionPayload
        }

        var cues: [CaptionCue] = []
        cues.reserveCapacity(events.count)

        for event in events {
            guard let startMs = number(event["tStartMs"]),
                  let segments = event["segs"] as? [[String: Any]] else {
                continue
            }

            let text = segments
                .compactMap { $0["utf8"] as? String }
                .joined()
                .replacingOccurrences(of: "\n", with: " ")
                .trimmingCharacters(in: .whitespacesAndNewlines)

            guard !text.isEmpty else { continue }

            let durationMs = number(event["dDurationMs"]) ?? 2500
            let start = startMs / 1000
            let end = start + max(durationMs / 1000, 0.1)

            cues.append(
                CaptionCue(
                    id: cues.count,
                    start: start,
                    end: end,
                    text: text
                )
            )
        }

        return cues
    }

    private static func number(_ value: Any?) -> Double? {
        if let number = value as? NSNumber {
            return number.doubleValue
        }

        if let string = value as? String {
            return Double(string)
        }

        return nil
    }

    private static func isAutoGenerated(track: [String: Any]) -> Bool {
        (track["kind"] as? String) == "asr"
            || ((track["vssId"] as? String)?.hasPrefix("a.") == true)
    }

    private static func text(from value: Any?) -> String? {
        guard let dictionary = value as? [String: Any] else { return nil }

        if let simpleText = dictionary["simpleText"] as? String {
            return simpleText
        }

        if let runs = dictionary["runs"] as? [[String: Any]] {
            let value = runs
                .compactMap { $0["text"] as? String }
                .joined()

            return value.isEmpty ? nil : value
        }

        return nil
    }

    private static func applyYouTubeHeaders(to request: inout URLRequest) {
        request.setValue(
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140 Safari/537.36",
            forHTTPHeaderField: "User-Agent"
        )
        request.setValue("cs-CZ,cs;q=0.9,en;q=0.7", forHTTPHeaderField: "Accept-Language")
        request.setValue("CONSENT=YES+cb.20210328-17-p0.en+FX+667", forHTTPHeaderField: "Cookie")
    }

    private static func extractPlayerResponse(from html: String) -> Data? {
        let markers = [
            "var ytInitialPlayerResponse = ",
            "ytInitialPlayerResponse = ",
            "window[\"ytInitialPlayerResponse\"] = ",
            "window['ytInitialPlayerResponse'] = "
        ]

        for marker in markers {
            guard let markerRange = html.range(of: marker) else { continue }
            let remainder = html[markerRange.upperBound...]

            guard let openingBrace = remainder.firstIndex(of: "{") else { continue }

            if let data = balancedJSONObjectData(from: remainder[openingBrace...]) {
                return data
            }
        }

        return nil
    }

    private static func balancedJSONObjectData(
        from substring: Substring
    ) -> Data? {
        let bytes = Array(substring.utf8)
        var depth = 0
        var inString = false
        var escaped = false

        for index in bytes.indices {
            let byte = bytes[index]

            if inString {
                if escaped {
                    escaped = false
                    continue
                }

                if byte == 0x5C {
                    escaped = true
                } else if byte == 0x22 {
                    inString = false
                }

                continue
            }

            if byte == 0x22 {
                inString = true
                continue
            }

            if byte == 0x7B {
                depth += 1
            } else if byte == 0x7D {
                depth -= 1

                if depth == 0 {
                    return Data(bytes[0...index])
                }
            }
        }

        return nil
    }
}
