import Foundation

struct CaptionTrack: Identifiable, Hashable {
    let id: String
    let languageCode: String
    let languageName: String
    let isAutoGenerated: Bool
    let isTranslated: Bool
    let url: URL
}

protocol CaptionServing {
    func preferredTrack(
        from tracks: [CaptionTrack],
        preferredLanguage: String,
        allowTranslation: Bool
    ) async throws -> CaptionTrack?
}

actor CaptionService: CaptionServing {
    func preferredTrack(
        from tracks: [CaptionTrack],
        preferredLanguage: String = "cs",
        allowTranslation: Bool = true
    ) async throws -> CaptionTrack? {
        if let native = tracks.first(where: { $0.languageCode == preferredLanguage && !$0.isTranslated }) {
            return native
        }

        if allowTranslation,
           let translated = tracks.first(where: { $0.languageCode == preferredLanguage && $0.isTranslated }) {
            return translated
        }

        return nil
    }
}
