import Foundation

struct CaptionCue: Identifiable, Hashable {
    let id: Int
    let start: TimeInterval
    let end: TimeInterval
    let text: String

    func contains(_ time: TimeInterval) -> Bool {
        time >= start && time < end
    }
}

struct CaptionResult: Hashable {
    let languageCode: String
    let displayName: String
    let isAutoGenerated: Bool
    let isTranslated: Bool
    let cues: [CaptionCue]
}

struct CaptionLanguageOption: Identifiable, Hashable {
    let id: String
    let languageCode: String
    let displayName: String
    let canTranslate: Bool
    let isNative: Bool
    let isAutoGenerated: Bool
}

enum CaptionServiceError: LocalizedError {
    case invalidVideoID
    case invalidResponse
    case captionDataNotFound
    case invalidCaptionURL
    case invalidCaptionPayload

    var errorDescription: String? {
        switch self {
        case .invalidVideoID:
            return "Neplatné video ID pro titulky."
        case .invalidResponse:
            return "YouTube nevrátil platnou odpověď pro titulky."
        case .captionDataNotFound:
            return "Video nemá dostupné titulky."
        case .invalidCaptionURL:
            return "Nepodařilo se sestavit adresu titulků."
        case .invalidCaptionPayload:
            return "YouTube vrátil titulky v neznámém formátu."
        }
    }
}

actor CaptionService {
    static let shared = CaptionService()

    func availableLanguages(
        videoID: String,
        preferredLanguage: String
    ) async throws -> [CaptionLanguageOption] {
        let renderer = try await captionRenderer(videoID: videoID)
        let tracks = renderer["captionTracks"] as? [[String: Any]] ?? []
        let translationLanguages =
            renderer["translationLanguages"] as? [[String: Any]] ?? []

        var options: [CaptionLanguageOption] = []
        var seen = Set<String>()

        for track in tracks {
            guard let code = track["languageCode"] as? String,
                  !code.isEmpty else {
                continue
            }

            let name = Self.text(from: track["name"]) ?? code
            let auto = Self.isAutoGenerated(track: track)
            let id = "native:\(code):\(auto ? "auto" : "manual")"

            guard seen.insert(id).inserted else { continue }

            options.append(
                CaptionLanguageOption(
                    id: id,
                    languageCode: code,
                    displayName: auto
                        ? "\(name) – \(L10n.text("automatic"))"
                        : name,
                    canTranslate: track["isTranslatable"] as? Bool ?? false,
                    isNative: true,
                    isAutoGenerated: auto
                )
            )
        }

        for language in translationLanguages {
            guard let code = language["languageCode"] as? String,
                  !code.isEmpty else {
                continue
            }

            let name = Self.text(from: language["languageName"]) ?? code
            let id = "translated:\(code)"

            guard seen.insert(id).inserted else { continue }

            options.append(
                CaptionLanguageOption(
                    id: id,
                    languageCode: code,
                    displayName:
                        "\(name) – \(L10n.text("automatic_translation"))",
                    canTranslate: true,
                    isNative: false,
                    isAutoGenerated: false
                )
            )
        }

        return options.sorted {
            let leftPreferred =
                Self.languageCode(
                    $0.languageCode,
                    matches: preferredLanguage
                )
            let rightPreferred =
                Self.languageCode(
                    $1.languageCode,
                    matches: preferredLanguage
                )

            if leftPreferred != rightPreferred {
                return leftPreferred
            }

            if $0.isNative != $1.isNative {
                return $0.isNative
            }

            return $0.displayName.localizedCaseInsensitiveCompare(
                $1.displayName
            ) == .orderedAscending
        }
    }

    func preferredCaptions(
        videoID: String,
        preferredLanguage: String,
        allowTranslation: Bool = true
    ) async throws -> CaptionResult? {
        try await captions(
            videoID: videoID,
            languageCode: preferredLanguage,
            preferTranslation: false,
            allowTranslation: allowTranslation
        )
    }

    func captions(
        videoID: String,
        languageCode: String,
        preferTranslation: Bool,
        allowTranslation: Bool = true
    ) async throws -> CaptionResult? {
        let renderer = try await captionRenderer(videoID: videoID)
        let tracks = renderer["captionTracks"] as? [[String: Any]] ?? []

        guard !tracks.isEmpty else {
            return nil
        }

        let translationLanguages = Set(
            (renderer["translationLanguages"] as? [[String: Any]] ?? [])
                .compactMap { $0["languageCode"] as? String }
        )

        if !preferTranslation {
            let exactTracks = tracks.filter {
                ($0["languageCode"] as? String)
                    == languageCode
            }
            let matchingTracks =
                exactTracks.isEmpty
                    ? tracks.filter {
                        guard let candidate =
                            $0["languageCode"] as? String else {
                            return false
                        }

                        return Self.languageCode(
                            candidate,
                            matches: languageCode
                        )
                    }
                    : exactTracks

            let nativeTrack = matchingTracks
                .sorted {
                    Self.isAutoGenerated(track: $0) == false
                        && Self.isAutoGenerated(track: $1) == true
                }
                .first

            if let nativeTrack {
                return try await loadTrack(
                    nativeTrack,
                    outputLanguage: languageCode,
                    translated: false
                )
            }
        }

        guard allowTranslation,
              translationLanguages.contains(languageCode) else {
            return nil
        }

        let translatableTracks = tracks.filter {
            ($0["isTranslatable"] as? Bool) == true
        }

        let originTrack =
            translatableTracks.first(where: {
                Self.isAutoGenerated(track: $0)
            })
            ?? translatableTracks.first
            ?? tracks.first

        guard let originTrack else {
            return nil
        }

        return try await loadTrack(
            originTrack,
            outputLanguage: languageCode,
            translated: true
        )
    }

    private func captionRenderer(
        videoID: String
    ) async throws -> [String: Any] {
        guard videoID.count == 11 else {
            throw CaptionServiceError.invalidVideoID
        }

        let watchURL = URL(
            string: "https://www.youtube.com/watch?v=\(videoID)&hl=\(L10n.currentLanguageCode)&gl=CZ"
        )!

        var request = URLRequest(url: watchURL)
        request.timeoutInterval = 20
        Self.applyYouTubeHeaders(to: &request)

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let http = response as? HTTPURLResponse,
              (200..<300).contains(http.statusCode),
              let html = String(data: data, encoding: .utf8) else {
            throw CaptionServiceError.invalidResponse
        }

        guard let playerData = Self.extractPlayerResponse(from: html),
              let root = try? JSONSerialization.jsonObject(
                with: playerData
              ) as? [String: Any],
              let captions = root["captions"] as? [String: Any],
              let renderer =
                captions["playerCaptionsTracklistRenderer"] as? [String: Any] else {
            throw CaptionServiceError.captionDataNotFound
        }

        return renderer
    }

    private func loadTrack(
        _ track: [String: Any],
        outputLanguage: String,
        translated: Bool
    ) async throws -> CaptionResult {
        guard let rawURL = track["baseUrl"] as? String,
              var components = URLComponents(string: rawURL) else {
            throw CaptionServiceError.invalidCaptionURL
        }

        var query = components.queryItems ?? []
        query.removeAll { $0.name == "fmt" || $0.name == "tlang" }
        query.append(URLQueryItem(name: "fmt", value: "json3"))

        if translated {
            query.append(URLQueryItem(name: "tlang", value: outputLanguage))
        }

        components.queryItems = query

        guard let url = components.url else {
            throw CaptionServiceError.invalidCaptionURL
        }

        var request = URLRequest(url: url)
        request.timeoutInterval = 20
        Self.applyYouTubeHeaders(to: &request)

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let http = response as? HTTPURLResponse,
              (200..<300).contains(http.statusCode),
              !data.isEmpty else {
            throw CaptionServiceError.invalidResponse
        }

        let cues = try Self.parseJSON3(data)

        guard !cues.isEmpty else {
            throw CaptionServiceError.invalidCaptionPayload
        }

        let originalName = Self.text(from: track["name"])
            ?? (track["languageCode"] as? String)
            ?? "Titulky"

        let translatedName = Locale(
            identifier: L10n.currentLanguageCode
        ).localizedString(forLanguageCode: outputLanguage)
            ?? outputLanguage

        return CaptionResult(
            languageCode: outputLanguage,
            displayName: translated
                ? "\(translatedName.capitalized) – \(L10n.text("automatic_translation"))"
                : originalName,
            isAutoGenerated: Self.isAutoGenerated(track: track),
            isTranslated: translated,
            cues: cues
        )
    }

    private static func languageCode(
        _ candidate: String,
        matches preferred: String
    ) -> Bool {
        if candidate.caseInsensitiveCompare(
            preferred
        ) == .orderedSame {
            return true
        }

        let candidateBase =
            candidate.split(separator: "-")
                .first
                .map(String.init)
                ?? candidate
        let preferredBase =
            preferred.split(separator: "-")
                .first
                .map(String.init)
                ?? preferred

        return candidateBase.caseInsensitiveCompare(
            preferredBase
        ) == .orderedSame
    }

    private static func parseJSON3(_ data: Data) throws -> [CaptionCue] {
        guard let root = try JSONSerialization.jsonObject(
            with: data
        ) as? [String: Any],
        let events = root["events"] as? [[String: Any]] else {
            throw CaptionServiceError.invalidCaptionPayload
        }

        var cues: [CaptionCue] = []
        cues.reserveCapacity(events.count)

        for event in events {
            guard let startMs = number(event["tStartMs"]),
                  let segments = event["segs"] as? [[String: Any]] else {
                continue
            }

            let text = segments
                .compactMap { $0["utf8"] as? String }
                .joined()
                .replacingOccurrences(of: "\n", with: " ")
                .trimmingCharacters(in: .whitespacesAndNewlines)

            guard !text.isEmpty else { continue }

            let durationMs = number(event["dDurationMs"]) ?? 2500
            let start = startMs / 1000
            let end = start + max(durationMs / 1000, 0.1)

            cues.append(
                CaptionCue(
                    id: cues.count,
                    start: start,
                    end: end,
                    text: text
                )
            )
        }

        return cues
    }

    private static func number(_ value: Any?) -> Double? {
        if let number = value as? NSNumber {
            return number.doubleValue
        }

        if let string = value as? String {
            return Double(string)
        }

        return nil
    }

    private static func isAutoGenerated(track: [String: Any]) -> Bool {
        (track["kind"] as? String) == "asr"
            || ((track["vssId"] as? String)?.hasPrefix("a.") == true)
    }

    private static func text(from value: Any?) -> String? {
        guard let dictionary = value as? [String: Any] else { return nil }

        if let simpleText = dictionary["simpleText"] as? String {
            return simpleText
        }

        if let runs = dictionary["runs"] as? [[String: Any]] {
            let value = runs
                .compactMap { $0["text"] as? String }
                .joined()

            return value.isEmpty ? nil : value
        }

        return nil
    }

    private static func applyYouTubeHeaders(to request: inout URLRequest) {
        request.setValue(
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140 Safari/537.36",
            forHTTPHeaderField: "User-Agent"
        )
        request.setValue(
            L10n.acceptLanguageHeader,
            forHTTPHeaderField: "Accept-Language"
        )
        request.setValue(
            "CONSENT=YES+cb.20210328-17-p0.en+FX+667",
            forHTTPHeaderField: "Cookie"
        )
    }

    private static func extractPlayerResponse(from html: String) -> Data? {
        let markers = [
            "var ytInitialPlayerResponse = ",
            "ytInitialPlayerResponse = ",
            "window[\"ytInitialPlayerResponse\"] = ",
            "window['ytInitialPlayerResponse'] = "
        ]

        for marker in markers {
            guard let markerRange = html.range(of: marker) else { continue }
            let remainder = html[markerRange.upperBound...]

            guard let openingBrace = remainder.firstIndex(of: "{") else {
                continue
            }

            if let data = balancedJSONObjectData(
                from: remainder[openingBrace...]
            ) {
                return data
            }
        }

        return nil
    }

    private static func balancedJSONObjectData(
        from substring: Substring
    ) -> Data? {
        let bytes = Array(substring.utf8)
        var depth = 0
        var inString = false
        var escaped = false

        for index in bytes.indices {
            let byte = bytes[index]

            if inString {
                if escaped {
                    escaped = false
                    continue
                }

                if byte == 0x5C {
                    escaped = true
                } else if byte == 0x22 {
                    inString = false
                }

                continue
            }

            if byte == 0x22 {
                inString = true
                continue
            }

            if byte == 0x7B {
                depth += 1
            } else if byte == 0x7D {
                depth -= 1

                if depth == 0 {
                    return Data(bytes[0...index])
                }
            }
        }

        return nil
    }
}
