import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case czech = "cs"
    case german = "de"
    case polish = "pl"
    case slovak = "sk"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english: return "English"
        case .czech: return "Čeština"
        case .german: return "Deutsch"
        case .polish: return "Polski"
        case .slovak: return "Slovenčina"
        }
    }
}

enum L10n {
    static func text(
        _ key: String,
        languageCode: String? = nil
    ) -> String {
        let code = languageCode
            ?? UserDefaults.standard.string(forKey: "appLanguage")
            ?? AppLanguage.english.rawValue

        return translations[code]?[key]
            ?? translations[AppLanguage.english.rawValue]?[key]
            ?? key
    }

    private static let translations: [String: [String: String]] = [
        "en": [
            "home": "Home",
            "subscriptions": "Subscriptions",
            "history": "History",
            "playlists": "Playlists",
            "search": "Search",
            "settings": "Settings",
            "recommended": "Recommended",
            "more_videos": "More videos",
            "videos": "Videos",
            "play": "Play",
            "playing": "Playback",
            "quality": "Quality",
            "automatic": "Automatic",
            "captions": "Subtitles",
            "captions_on": "On",
            "captions_off": "Off",
            "speed": "Speed",
            "normal_speed": "Normal",
            "loading_stream": "Finding stream…",
            "preparing_video": "Preparing video…",
            "switching_quality": "Switching quality…",
            "loading_captions": "Loading subtitles…",
            "loading_czech_captions": "Loading Czech subtitles…",
            "captions_unavailable": "Subtitles are not available",
            "czech_automatic": "Czech – automatic",
            "current_playback": "Currently playing",
            "search_placeholder": "Search YouTube or paste a URL / video ID",
            "play_pasted_video": "Play pasted YouTube video",
            "youtube_no_videos": "YouTube returned no videos.",
            "youtube_no_playlists": "YouTube returned no playlists.",
            "playlist_empty": "This playlist has no available videos.",
            "loading_playlist": "Loading playlist…",
            "loading_channel": "Loading channel…",
            "channel_no_videos": "This channel returned no available videos.",
            "sign_in_hint": "Sign in under Settings → Account.",
            "playback_section": "Playback",
            "preferred_quality": "Preferred quality",
            "hdr_available": "HDR output is available",
            "hdr_unavailable": "HDR output is currently unavailable",
            "ads_active": "Ads: blocking active",
            "ads_description": "TubeTV does not pass YouTube ad placements to AVPlayer and prefers direct content video/audio streams.",
            "subtitles_section": "Subtitles",
            "auto_enable_subtitles": "Automatically enable subtitles",
            "auto_translate_subtitles": "Automatically translate subtitles",
            "preferred_subtitle_language": "Preferred subtitle language",
            "subtitle_fallback_description": "When the preferred subtitle track is unavailable, TubeTV can use an available or auto-generated track and translate it.",
            "language_section": "Language",
            "app_language": "App language",
            "language_restart_note": "The interface language changes immediately on supported screens.",
            "youtube_account": "YouTube Account",
            "signed_in": "Signed in to YouTube",
            "youtube_profile": "YouTube profile",
            "refresh_profiles": "Refresh profiles",
            "sign_out": "Sign out",
            "sign_in": "Sign in to YouTube",
            "waiting_confirmation": "Waiting for confirmation…",
            "open_on_phone": "Open on your phone or computer:",
            "enter_code": "Enter code:",
            "waiting_sign_in": "TubeTV is waiting for sign-in to finish.",
            "smarttube_login_description": "TubeTV uses a SmartTube-style YouTube TV device login, stores the refresh token in Keychain, and supports Brand Accounts.",
            "profile_active": "Active YouTube profile",
            "profiles_found": "YouTube profiles found",
            "sign_in_complete": "Sign-in completed.",
            "signed_out": "YouTube account signed out.",
            "profile_error": "Profiles",
            "subtitles_preferred_status": "Subtitles",
            "test": "TEST"
        ],
        "cs": [
            "home": "Domů",
            "subscriptions": "Odběry",
            "history": "Historie",
            "playlists": "Playlisty",
            "search": "Hledat",
            "settings": "Nastavení",
            "recommended": "Doporučené",
            "more_videos": "Další videa",
            "videos": "Videa",
            "play": "Přehrát",
            "playing": "Přehrávání",
            "quality": "Kvalita",
            "automatic": "Automaticky",
            "captions": "Titulky",
            "captions_on": "Zapnuto",
            "captions_off": "Vypnuto",
            "speed": "Rychlost",
            "normal_speed": "Normální",
            "loading_stream": "Hledám stream…",
            "preparing_video": "Připravuji video…",
            "switching_quality": "Měním kvalitu…",
            "loading_captions": "Načítám titulky…",
            "loading_czech_captions": "Načítám české titulky…",
            "captions_unavailable": "Titulky nejsou dostupné",
            "czech_automatic": "Čeština – automaticky",
            "current_playback": "Aktuálně přehráváno",
            "search_placeholder": "Hledat na YouTube nebo vložit URL / video ID",
            "play_pasted_video": "Přehrát vložené YouTube video",
            "youtube_no_videos": "YouTube nevrátil žádná videa.",
            "youtube_no_playlists": "YouTube nevrátil žádné playlisty.",
            "playlist_empty": "Playlist neobsahuje žádná dostupná videa.",
            "loading_playlist": "Načítám playlist…",
            "loading_channel": "Načítám kanál…",
            "channel_no_videos": "Kanál nevrátil žádná dostupná videa.",
            "sign_in_hint": "Přihlášení najdeš v Nastavení → Účet.",
            "playback_section": "Přehrávání",
            "preferred_quality": "Preferovaná kvalita",
            "hdr_available": "HDR výstup je dostupný",
            "hdr_unavailable": "HDR výstup aktuálně není dostupný",
            "ads_active": "Reklamy: blokování aktivní",
            "ads_description": "TubeTV nepředává YouTube reklamní placementy do AVPlayeru a preferuje přímé obsahové video/audio streamy.",
            "subtitles_section": "Titulky",
            "auto_enable_subtitles": "Automaticky zapnout titulky",
            "auto_translate_subtitles": "Automaticky překládat titulky",
            "preferred_subtitle_language": "Preferovaný jazyk titulků",
            "subtitle_fallback_description": "Když preferovaná stopa není dostupná, TubeTV může použít dostupnou nebo automaticky generovanou stopu a přeložit ji.",
            "language_section": "Jazyk",
            "app_language": "Jazyk aplikace",
            "language_restart_note": "Jazyk rozhraní se na podporovaných obrazovkách změní okamžitě.",
            "youtube_account": "YouTube účet",
            "signed_in": "Přihlášeno k YouTube",
            "youtube_profile": "YouTube profil",
            "refresh_profiles": "Obnovit profily",
            "sign_out": "Odhlásit účet",
            "sign_in": "Přihlásit YouTube účet",
            "waiting_confirmation": "Čekám na potvrzení…",
            "open_on_phone": "Na telefonu nebo počítači otevři:",
            "enter_code": "Zadej kód:",
            "waiting_sign_in": "TubeTV čeká na dokončení přihlášení.",
            "smarttube_login_description": "TubeTV používá SmartTube-style YouTube TV device login, refresh token v Keychainu a podporuje Brand účty.",
            "profile_active": "Aktivní YouTube profil",
            "profiles_found": "Nalezené YouTube profily",
            "sign_in_complete": "Přihlášení bylo dokončeno.",
            "signed_out": "YouTube účet byl odhlášen.",
            "profile_error": "Profily",
            "subtitles_preferred_status": "Titulky",
            "test": "TEST"
        ],
        "de": [
            "home": "Start",
            "subscriptions": "Abos",
            "history": "Verlauf",
            "playlists": "Playlists",
            "search": "Suchen",
            "settings": "Einstellungen",
            "recommended": "Empfohlen",
            "more_videos": "Weitere Videos",
            "videos": "Videos",
            "play": "Abspielen",
            "playing": "Wiedergabe",
            "quality": "Qualität",
            "automatic": "Automatisch",
            "captions": "Untertitel",
            "captions_on": "Ein",
            "captions_off": "Aus",
            "speed": "Geschwindigkeit",
            "normal_speed": "Normal",
            "search_placeholder": "YouTube durchsuchen oder URL / Video-ID einfügen",
            "play_pasted_video": "Eingefügtes YouTube-Video abspielen",
            "playback_section": "Wiedergabe",
            "preferred_quality": "Bevorzugte Qualität",
            "subtitles_section": "Untertitel",
            "auto_enable_subtitles": "Untertitel automatisch aktivieren",
            "auto_translate_subtitles": "Untertitel automatisch übersetzen",
            "preferred_subtitle_language": "Bevorzugte Untertitelsprache",
            "language_section": "Sprache",
            "app_language": "App-Sprache",
            "youtube_account": "YouTube-Konto",
            "signed_in": "Bei YouTube angemeldet",
            "youtube_profile": "YouTube-Profil",
            "refresh_profiles": "Profile aktualisieren",
            "sign_out": "Abmelden",
            "sign_in": "Bei YouTube anmelden"
        ],
        "pl": [
            "home": "Strona główna",
            "subscriptions": "Subskrypcje",
            "history": "Historia",
            "playlists": "Playlisty",
            "search": "Szukaj",
            "settings": "Ustawienia",
            "recommended": "Polecane",
            "more_videos": "Więcej filmów",
            "videos": "Filmy",
            "play": "Odtwórz",
            "playing": "Odtwarzanie",
            "quality": "Jakość",
            "automatic": "Automatycznie",
            "captions": "Napisy",
            "captions_on": "Włączone",
            "captions_off": "Wyłączone",
            "speed": "Prędkość",
            "normal_speed": "Normalna",
            "search_placeholder": "Szukaj w YouTube lub wklej URL / ID filmu",
            "play_pasted_video": "Odtwórz wklejony film YouTube",
            "playback_section": "Odtwarzanie",
            "preferred_quality": "Preferowana jakość",
            "subtitles_section": "Napisy",
            "auto_enable_subtitles": "Automatycznie włączaj napisy",
            "auto_translate_subtitles": "Automatycznie tłumacz napisy",
            "preferred_subtitle_language": "Preferowany język napisów",
            "language_section": "Język",
            "app_language": "Język aplikacji",
            "youtube_account": "Konto YouTube",
            "signed_in": "Zalogowano do YouTube",
            "youtube_profile": "Profil YouTube",
            "refresh_profiles": "Odśwież profile",
            "sign_out": "Wyloguj",
            "sign_in": "Zaloguj do YouTube"
        ],
        "sk": [
            "home": "Domov",
            "subscriptions": "Odbery",
            "history": "História",
            "playlists": "Playlisty",
            "search": "Hľadať",
            "settings": "Nastavenia",
            "recommended": "Odporúčané",
            "more_videos": "Ďalšie videá",
            "videos": "Videá",
            "play": "Prehrať",
            "playing": "Prehrávanie",
            "quality": "Kvalita",
            "automatic": "Automaticky",
            "captions": "Titulky",
            "captions_on": "Zapnuté",
            "captions_off": "Vypnuté",
            "speed": "Rýchlosť",
            "normal_speed": "Normálna",
            "search_placeholder": "Hľadať na YouTube alebo vložiť URL / ID videa",
            "play_pasted_video": "Prehrať vložené YouTube video",
            "playback_section": "Prehrávanie",
            "preferred_quality": "Preferovaná kvalita",
            "subtitles_section": "Titulky",
            "auto_enable_subtitles": "Automaticky zapnúť titulky",
            "auto_translate_subtitles": "Automaticky prekladať titulky",
            "preferred_subtitle_language": "Preferovaný jazyk titulkov",
            "language_section": "Jazyk",
            "app_language": "Jazyk aplikácie",
            "youtube_account": "YouTube účet",
            "signed_in": "Prihlásené k YouTube",
            "youtube_profile": "YouTube profil",
            "refresh_profiles": "Obnoviť profily",
            "sign_out": "Odhlásiť účet",
            "sign_in": "Prihlásiť YouTube účet"
        ]
    ]
}
