import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case czech = "cs"
    case german = "de"
    case polish = "pl"
    case slovak = "sk"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english: return "English"
        case .czech: return "Čeština"
        case .german: return "Deutsch"
        case .polish: return "Polski"
        case .slovak: return "Slovenčina"
        }
    }
}

enum L10n {
    static var currentLanguageCode: String {
        UserDefaults.standard.string(forKey: "appLanguage")
            ?? AppLanguage.english.rawValue
    }

    static var acceptLanguageHeader: String {
        let code = currentLanguageCode

        if code == "en" {
            return "en-US,en;q=0.9"
        }

        return "\(code),en;q=0.8"
    }

    static func text(
        _ key: String,
        languageCode: String? = nil
    ) -> String {
        let code = languageCode
            ?? UserDefaults.standard.string(forKey: "appLanguage")
            ?? AppLanguage.english.rawValue

        return translations[code]?[key]
            ?? translations[AppLanguage.english.rawValue]?[key]
            ?? key
    }

    private static let translations: [String: [String: String]] = [
        "en": [
            "home": "Home",
            "subscriptions": "Subscriptions",
            "channels": "Channels",
            "history": "History",
            "playlists": "Playlists",
            "save_to_playlist": "Save to playlist",
            "manage_playlists": "Choose playlists",
            "loading_playlists": "Loading playlists…",
            "create_playlist": "Create",
            "new_playlist_name": "New playlist name",
            "search": "Search",
            "settings": "Settings",
            "recommended": "Recommended",
            "more_videos": "More videos",
            "videos": "Videos",
            "subscribe_channel": "Subscribe",
            "unsubscribe_channel": "Subscribed",
            "play": "Play",
            "playing": "Playback",
            "like": "Like",
            "dislike": "Dislike",
            "quality": "Quality",
            "automatic": "Automatic",
            "automatic_translation": "Automatic translation",
            "audio": "Audio",
            "original_audio": "Original",
            "captions": "Subtitles",
            "captions_on": "On",
            "captions_off": "Off",
            "speed": "Speed",
            "normal_speed": "Normal",
            "loading_stream": "Finding stream…",
            "preparing_video": "Preparing video…",
            "switching_quality": "Switching quality…",
            "loading_captions": "Loading subtitles…",
            "captions_unavailable": "Subtitles are not available",
            "current_playback": "Currently playing",
            "search_placeholder": "Search YouTube or paste a URL / video ID",
            "play_pasted_video": "Play pasted YouTube video",
            "youtube_no_videos": "YouTube returned no videos.",
            "youtube_no_channels": "YouTube returned no subscribed channels.",
            "youtube_no_playlists": "YouTube returned no playlists.",
            "playlist_empty": "This playlist has no available videos.",
            "loading_playlist": "Loading playlist…",
            "loading_channel": "Loading channel…",
            "channel_no_videos": "This channel returned no available videos.",
            "sign_in_hint": "Sign in under Settings → Account.",
            "playback_section": "Playback",
            "preferred_quality": "Preferred quality",
            "hdr_available": "HDR output is available",
            "hdr_unavailable": "HDR output is currently unavailable",
            "ads_active": "Ads: blocking active",
            "ads_description": "TubeTV does not pass YouTube ad placements to AVPlayer and prefers direct content video/audio streams.",
            "subtitles_section": "Subtitles",
            "auto_enable_subtitles": "Automatically enable subtitles",
            "auto_translate_subtitles": "Automatically translate subtitles",
            "preferred_subtitle_language": "Preferred subtitle language",
            "subtitle_fallback_description": "When the preferred subtitle track is unavailable, TubeTV can use an available or auto-generated track and translate it.",
            "language_section": "Language",
            "app_language": "App language",
            "language_restart_note": "The interface language changes immediately on supported screens.",
            "youtube_account": "YouTube Account",
            "signed_in": "Signed in to YouTube",
            "youtube_profile": "YouTube profile",
            "refresh_profiles": "Refresh profiles",
            "sign_out": "Sign out",
            "sign_in": "Sign in to YouTube",
            "waiting_confirmation": "Waiting for confirmation…",
            "open_on_phone": "Open on your phone or computer:",
            "enter_code": "Enter code:",
            "waiting_sign_in": "TubeTV is waiting for sign-in to finish.",
            "smarttube_login_description": "TubeTV uses a SmartTube-style YouTube TV device login, stores the refresh token in Keychain, and supports Brand Accounts.",
            "profile_active": "Active YouTube profile",
            "profiles_found": "YouTube profiles found",
            "sign_in_complete": "Sign-in completed.",
            "signed_out": "YouTube account signed out.",
            "profile_error": "Profiles",
            "subtitles_preferred_status": "Subtitles",
            "no_playback_source": "This video does not have a playable source yet.",
            "adaptive_fallback": "Higher quality could not be combined. Playing a compatible version.",
            "quality_change_error": "Quality change",
            "loading_languages": "Loading available languages…",
            "auth_tv_page_unavailable": "Could not load YouTube TV.",
            "auth_client_script_not_found": "YouTube TV did not provide the sign-in script.",
            "auth_credentials_not_found": "Could not determine the current YouTube TV sign-in credentials.",
            "auth_invalid_response": "YouTube returned an invalid response.",
            "auth_denied": "Sign-in was denied.",
            "auth_expired": "The sign-in code expired.",
            "auth_not_signed_in": "You are not signed in to YouTube.",
            "auth_refresh_failed": "Refreshing the YouTube sign-in failed.",
            "caption_error_invalid_video": "Invalid video ID for subtitles.",
            "caption_error_invalid_response": "YouTube returned an invalid subtitle response.",
            "caption_error_not_found": "This video has no available subtitles.",
            "caption_error_invalid_url": "Could not create the subtitle URL.",
            "caption_error_invalid_payload": "YouTube returned subtitles in an unknown format.",
            "authenticated_player_not_signed_in": "The YouTube account is not signed in.",
            "authenticated_player_invalid_response": "The signed-in YouTube player returned an invalid response.",
            "authenticated_player_unavailable": "This video is not available for this account.",
            "authenticated_player_no_stream": "The signed-in YouTube player did not return a stream compatible with Apple TV.",
            "youtube_request_invalid": "Could not create the YouTube request.",
            "youtube_response_invalid": "YouTube returned an invalid response.",
            "youtube_page_data_missing": "Could not load YouTube data. The page structure may have changed.",
            "unknown": "Unknown",
            "invalid_video_id": "Invalid YouTube video ID.",
            "no_playable_stream": "No Apple TV-compatible stream was found for this video.",
            "youtube_network_blocked": "YouTube is temporarily blocking this network. Disable your VPN, try a different VPN server, or wait a few minutes and try again.",
            "youtube_sign_in_required": "This video is age-restricted or requires sign-in to watch.",
        ],
        "cs": [
            "home": "Domů",
            "subscriptions": "Odběry",
            "channels": "Kanály",
            "history": "Historie",
            "playlists": "Playlisty",
            "save_to_playlist": "Uložit do playlistu",
            "manage_playlists": "Vybrat playlisty",
            "loading_playlists": "Načítám playlisty…",
            "create_playlist": "Vytvořit",
            "new_playlist_name": "Název nového playlistu",
            "search": "Hledat",
            "settings": "Nastavení",
            "recommended": "Doporučené",
            "more_videos": "Další videa",
            "videos": "Videa",
            "subscribe_channel": "Odebírat",
            "unsubscribe_channel": "Odebíráno",
            "play": "Přehrát",
            "playing": "Přehrávání",
            "like": "To se mi líbí",
            "dislike": "To se mi nelíbí",
            "quality": "Kvalita",
            "automatic": "Automaticky",
            "automatic_translation": "Automatický překlad",
            "audio": "Zvuk",
            "original_audio": "Originál",
            "captions": "Titulky",
            "captions_on": "Zapnuto",
            "captions_off": "Vypnuto",
            "speed": "Rychlost",
            "normal_speed": "Normální",
            "loading_stream": "Hledám stream…",
            "preparing_video": "Připravuji video…",
            "switching_quality": "Měním kvalitu…",
            "loading_captions": "Načítám titulky…",
            "captions_unavailable": "Titulky nejsou dostupné",
            "current_playback": "Aktuálně přehráváno",
            "search_placeholder": "Hledat na YouTube nebo vložit URL / video ID",
            "play_pasted_video": "Přehrát vložené YouTube video",
            "youtube_no_videos": "YouTube nevrátil žádná videa.",
            "youtube_no_channels": "YouTube nevrátil žádné odebírané kanály.",
            "youtube_no_playlists": "YouTube nevrátil žádné playlisty.",
            "playlist_empty": "Playlist neobsahuje žádná dostupná videa.",
            "loading_playlist": "Načítám playlist…",
            "loading_channel": "Načítám kanál…",
            "channel_no_videos": "Kanál nevrátil žádná dostupná videa.",
            "sign_in_hint": "Přihlášení najdeš v Nastavení → Účet.",
            "playback_section": "Přehrávání",
            "preferred_quality": "Preferovaná kvalita",
            "hdr_available": "HDR výstup je dostupný",
            "hdr_unavailable": "HDR výstup aktuálně není dostupný",
            "ads_active": "Reklamy: blokování aktivní",
            "ads_description": "TubeTV nepředává YouTube reklamní placementy do AVPlayeru a preferuje přímé obsahové video/audio streamy.",
            "subtitles_section": "Titulky",
            "auto_enable_subtitles": "Automaticky zapnout titulky",
            "auto_translate_subtitles": "Automaticky překládat titulky",
            "preferred_subtitle_language": "Preferovaný jazyk titulků",
            "subtitle_fallback_description": "Když preferovaná stopa není dostupná, TubeTV může použít dostupnou nebo automaticky generovanou stopu a přeložit ji.",
            "language_section": "Jazyk",
            "app_language": "Jazyk aplikace",
            "language_restart_note": "Jazyk rozhraní se na podporovaných obrazovkách změní okamžitě.",
            "youtube_account": "YouTube účet",
            "signed_in": "Přihlášeno k YouTube",
            "youtube_profile": "YouTube profil",
            "refresh_profiles": "Obnovit profily",
            "sign_out": "Odhlásit účet",
            "sign_in": "Přihlásit YouTube účet",
            "waiting_confirmation": "Čekám na potvrzení…",
            "open_on_phone": "Na telefonu nebo počítači otevři:",
            "enter_code": "Zadej kód:",
            "waiting_sign_in": "TubeTV čeká na dokončení přihlášení.",
            "smarttube_login_description": "TubeTV používá SmartTube-style YouTube TV device login, refresh token v Keychainu a podporuje Brand účty.",
            "profile_active": "Aktivní YouTube profil",
            "profiles_found": "Nalezené YouTube profily",
            "sign_in_complete": "Přihlášení bylo dokončeno.",
            "signed_out": "YouTube účet byl odhlášen.",
            "profile_error": "Profily",
            "subtitles_preferred_status": "Titulky",
            "no_playback_source": "Toto video zatím nemá zdroj pro přehrávání.",
            "adaptive_fallback": "Vyšší kvalita nešla spojit, přehrávám kompatibilní variantu.",
            "quality_change_error": "Změna kvality",
            "loading_languages": "Načítám dostupné jazyky…",
            "auth_tv_page_unavailable": "Nepodařilo se načíst YouTube TV.",
            "auth_client_script_not_found": "YouTube TV nevrátil přihlašovací skript.",
            "auth_credentials_not_found": "Nepodařilo se zjistit aktuální YouTube TV přihlašovací údaje.",
            "auth_invalid_response": "YouTube vrátil neplatnou odpověď.",
            "auth_denied": "Přihlášení bylo zamítnuto.",
            "auth_expired": "Přihlašovací kód vypršel.",
            "auth_not_signed_in": "Nejsi přihlášen k YouTube.",
            "auth_refresh_failed": "Obnovení přihlášení k YouTube selhalo.",
            "caption_error_invalid_video": "Neplatné video ID pro titulky.",
            "caption_error_invalid_response": "YouTube nevrátil platnou odpověď pro titulky.",
            "caption_error_not_found": "Video nemá dostupné titulky.",
            "caption_error_invalid_url": "Nepodařilo se sestavit adresu titulků.",
            "caption_error_invalid_payload": "YouTube vrátil titulky v neznámém formátu.",
            "authenticated_player_not_signed_in": "YouTube účet není přihlášen.",
            "authenticated_player_invalid_response": "Přihlášený YouTube přehrávač vrátil neplatnou odpověď.",
            "authenticated_player_unavailable": "Video není pro tento účet dostupné.",
            "authenticated_player_no_stream": "Přihlášený YouTube přehrávač nevrátil stream vhodný pro Apple TV.",
            "youtube_request_invalid": "Nepodařilo se sestavit požadavek na YouTube.",
            "youtube_response_invalid": "YouTube vrátil neplatnou odpověď.",
            "youtube_page_data_missing": "Nepodařilo se načíst data YouTube. Struktura stránky se mohla změnit.",
            "unknown": "Neznámé",
            "invalid_video_id": "Neplatné YouTube video ID.",
            "no_playable_stream": "Pro toto video se nepodařilo najít stream přehratelný na Apple TV.",
            "youtube_network_blocked": "YouTube tuto síť dočasně blokuje. Vypni VPN, zkus jiný VPN server nebo několik minut počkej a zkus to znovu.",
            "youtube_sign_in_required": "Toto video je věkově omezené nebo vyžaduje přihlášení.",
        ],
        "de": [
            "home": "Start",
            "subscriptions": "Abos",
            "channels": "Kanäle",
            "history": "Verlauf",
            "playlists": "Playlists",
            "save_to_playlist": "In Playlist speichern",
            "manage_playlists": "Playlists auswählen",
            "loading_playlists": "Playlists werden geladen…",
            "create_playlist": "Erstellen",
            "new_playlist_name": "Name der neuen Playlist",
            "search": "Suchen",
            "settings": "Einstellungen",
            "youtube_no_channels": "YouTube hat keine abonnierten Kanäle zurückgegeben.",
            "recommended": "Empfohlen",
            "more_videos": "Weitere Videos",
            "videos": "Videos",
            "subscribe_channel": "Abonnieren",
            "unsubscribe_channel": "Abonniert",
            "play": "Abspielen",
            "playing": "Wiedergabe",
            "like": "Gefällt mir",
            "dislike": "Gefällt mir nicht",
            "quality": "Qualität",
            "automatic": "Automatisch",
            "automatic_translation": "Automatische Übersetzung",
            "audio": "Audio",
            "original_audio": "Original",
            "captions": "Untertitel",
            "captions_on": "Ein",
            "captions_off": "Aus",
            "speed": "Geschwindigkeit",
            "normal_speed": "Normal",
            "search_placeholder": "YouTube durchsuchen oder URL / Video-ID einfügen",
            "play_pasted_video": "Eingefügtes YouTube-Video abspielen",
            "playback_section": "Wiedergabe",
            "preferred_quality": "Bevorzugte Qualität",
            "subtitles_section": "Untertitel",
            "auto_enable_subtitles": "Untertitel automatisch aktivieren",
            "auto_translate_subtitles": "Untertitel automatisch übersetzen",
            "preferred_subtitle_language": "Bevorzugte Untertitelsprache",
            "language_section": "Sprache",
            "app_language": "App-Sprache",
            "youtube_account": "YouTube-Konto",
            "signed_in": "Bei YouTube angemeldet",
            "youtube_profile": "YouTube-Profil",
            "refresh_profiles": "Profile aktualisieren",
            "sign_out": "Abmelden",
            "sign_in": "Bei YouTube anmelden",
            "loading_stream": "Stream wird gesucht…",
            "preparing_video": "Video wird vorbereitet…",
            "switching_quality": "Qualität wird gewechselt…",
            "loading_captions": "Untertitel werden geladen…",
            "captions_unavailable": "Untertitel sind nicht verfügbar",
            "current_playback": "Aktuelle Wiedergabe",
            "youtube_no_videos": "YouTube hat keine Videos zurückgegeben.",
            "youtube_no_playlists": "YouTube hat keine Playlists zurückgegeben.",
            "playlist_empty": "Diese Playlist enthält keine verfügbaren Videos.",
            "loading_playlist": "Playlist wird geladen…",
            "loading_channel": "Kanal wird geladen…",
            "channel_no_videos": "Dieser Kanal hat keine verfügbaren Videos zurückgegeben.",
            "sign_in_hint": "Melde dich unter Einstellungen → Konto an.",
            "hdr_available": "HDR-Ausgabe ist verfügbar",
            "hdr_unavailable": "HDR-Ausgabe ist derzeit nicht verfügbar",
            "ads_active": "Werbung: Blockierung aktiv",
            "ads_description": "TubeTV übergibt YouTube-Werbeplatzierungen nicht an AVPlayer und bevorzugt direkte Video-/Audio-Inhaltsstreams.",
            "subtitle_fallback_description": "Wenn die bevorzugte Untertitelspur nicht verfügbar ist, kann TubeTV eine verfügbare oder automatisch erzeugte Spur verwenden und übersetzen.",
            "language_restart_note": "Die Sprache der Oberfläche ändert sich auf unterstützten Bildschirmen sofort.",
            "waiting_confirmation": "Warten auf Bestätigung…",
            "open_on_phone": "Auf dem Telefon oder Computer öffnen:",
            "enter_code": "Code eingeben:",
            "waiting_sign_in": "TubeTV wartet auf den Abschluss der Anmeldung.",
            "smarttube_login_description": "TubeTV verwendet eine YouTube-TV-Geräteanmeldung im SmartTube-Stil, speichert das Aktualisierungstoken im Schlüsselbund und unterstützt Brand-Konten.",
            "profile_active": "Aktives YouTube-Profil",
            "profiles_found": "YouTube-Profile gefunden",
            "sign_in_complete": "Anmeldung abgeschlossen.",
            "signed_out": "YouTube-Konto wurde abgemeldet.",
            "profile_error": "Profile",
            "subtitles_preferred_status": "Untertitel",
            "no_playback_source": "Für dieses Video ist noch keine abspielbare Quelle verfügbar.",
            "adaptive_fallback": "Die höhere Qualität konnte nicht kombiniert werden. Eine kompatible Version wird abgespielt.",
            "quality_change_error": "Qualitätswechsel",
            "loading_languages": "Verfügbare Sprachen werden geladen…",
            "auth_tv_page_unavailable": "YouTube TV konnte nicht geladen werden.",
            "auth_client_script_not_found": "YouTube TV hat das Anmeldeskript nicht bereitgestellt.",
            "auth_credentials_not_found": "Die aktuellen YouTube-TV-Anmeldedaten konnten nicht ermittelt werden.",
            "auth_invalid_response": "YouTube hat eine ungültige Antwort zurückgegeben.",
            "auth_denied": "Die Anmeldung wurde abgelehnt.",
            "auth_expired": "Der Anmeldecode ist abgelaufen.",
            "auth_not_signed_in": "Du bist nicht bei YouTube angemeldet.",
            "auth_refresh_failed": "Die YouTube-Anmeldung konnte nicht aktualisiert werden.",
            "caption_error_invalid_video": "Ungültige Video-ID für Untertitel.",
            "caption_error_invalid_response": "YouTube hat eine ungültige Untertitelantwort zurückgegeben.",
            "caption_error_not_found": "Für dieses Video sind keine Untertitel verfügbar.",
            "caption_error_invalid_url": "Die Untertitel-URL konnte nicht erstellt werden.",
            "caption_error_invalid_payload": "YouTube hat Untertitel in einem unbekannten Format zurückgegeben.",
            "authenticated_player_not_signed_in": "Das YouTube-Konto ist nicht angemeldet.",
            "authenticated_player_invalid_response": "Der angemeldete YouTube-Player hat eine ungültige Antwort zurückgegeben.",
            "authenticated_player_unavailable": "Dieses Video ist für dieses Konto nicht verfügbar.",
            "authenticated_player_no_stream": "Der angemeldete YouTube-Player hat keinen mit Apple TV kompatiblen Stream zurückgegeben.",
            "youtube_request_invalid": "Die YouTube-Anfrage konnte nicht erstellt werden.",
            "youtube_response_invalid": "YouTube hat eine ungültige Antwort zurückgegeben.",
            "youtube_page_data_missing": "YouTube-Daten konnten nicht geladen werden. Die Seitenstruktur könnte sich geändert haben.",
            "unknown": "Unbekannt",
            "invalid_video_id": "Ungültige YouTube-Video-ID.",
            "no_playable_stream": "Für dieses Video wurde kein mit Apple TV kompatibler Stream gefunden.",
            "youtube_network_blocked": "YouTube blockiert dieses Netzwerk vorübergehend. Deaktiviere dein VPN, wechsle den VPN-Server oder versuche es in einigen Minuten erneut.",
            "youtube_sign_in_required": "Dieses Video ist altersbeschränkt oder erfordert eine Anmeldung."
        ],
        "pl": [
            "home": "Strona główna",
            "subscriptions": "Subskrypcje",
            "channels": "Kanały",
            "history": "Historia",
            "playlists": "Playlisty",
            "save_to_playlist": "Zapisz na playliście",
            "manage_playlists": "Wybierz playlisty",
            "loading_playlists": "Ładowanie playlist…",
            "create_playlist": "Utwórz",
            "new_playlist_name": "Nazwa nowej playlisty",
            "search": "Szukaj",
            "settings": "Ustawienia",
            "youtube_no_channels": "YouTube nie zwrócił żadnych subskrybowanych kanałów.",
            "recommended": "Polecane",
            "more_videos": "Więcej filmów",
            "videos": "Filmy",
            "subscribe_channel": "Subskrybuj",
            "unsubscribe_channel": "Subskrybowano",
            "play": "Odtwórz",
            "playing": "Odtwarzanie",
            "like": "Lubię to",
            "dislike": "Nie lubię",
            "quality": "Jakość",
            "automatic": "Automatycznie",
            "automatic_translation": "Tłumaczenie automatyczne",
            "audio": "Dźwięk",
            "original_audio": "Oryginał",
            "captions": "Napisy",
            "captions_on": "Włączone",
            "captions_off": "Wyłączone",
            "speed": "Prędkość",
            "normal_speed": "Normalna",
            "search_placeholder": "Szukaj w YouTube lub wklej URL / ID filmu",
            "play_pasted_video": "Odtwórz wklejony film YouTube",
            "playback_section": "Odtwarzanie",
            "preferred_quality": "Preferowana jakość",
            "subtitles_section": "Napisy",
            "auto_enable_subtitles": "Automatycznie włączaj napisy",
            "auto_translate_subtitles": "Automatycznie tłumacz napisy",
            "preferred_subtitle_language": "Preferowany język napisów",
            "language_section": "Język",
            "app_language": "Język aplikacji",
            "youtube_account": "Konto YouTube",
            "signed_in": "Zalogowano do YouTube",
            "youtube_profile": "Profil YouTube",
            "refresh_profiles": "Odśwież profile",
            "sign_out": "Wyloguj",
            "sign_in": "Zaloguj do YouTube",
            "loading_stream": "Wyszukiwanie strumienia…",
            "preparing_video": "Przygotowywanie filmu…",
            "switching_quality": "Zmiana jakości…",
            "loading_captions": "Ładowanie napisów…",
            "captions_unavailable": "Napisy są niedostępne",
            "current_playback": "Aktualne odtwarzanie",
            "youtube_no_videos": "YouTube nie zwrócił żadnych filmów.",
            "youtube_no_playlists": "YouTube nie zwrócił żadnych playlist.",
            "playlist_empty": "Ta playlista nie zawiera dostępnych filmów.",
            "loading_playlist": "Ładowanie playlisty…",
            "loading_channel": "Ładowanie kanału…",
            "channel_no_videos": "Ten kanał nie zwrócił żadnych dostępnych filmów.",
            "sign_in_hint": "Zaloguj się w Ustawienia → Konto.",
            "hdr_available": "Wyjście HDR jest dostępne",
            "hdr_unavailable": "Wyjście HDR jest obecnie niedostępne",
            "ads_active": "Reklamy: blokowanie aktywne",
            "ads_description": "TubeTV nie przekazuje umiejscowień reklam YouTube do AVPlayera i preferuje bezpośrednie strumienie wideo/audio z treścią.",
            "subtitle_fallback_description": "Jeśli preferowana ścieżka napisów jest niedostępna, TubeTV może użyć dostępnej lub automatycznie wygenerowanej ścieżki i ją przetłumaczyć.",
            "language_restart_note": "Język interfejsu zmienia się natychmiast na obsługiwanych ekranach.",
            "waiting_confirmation": "Oczekiwanie na potwierdzenie…",
            "open_on_phone": "Otwórz na telefonie lub komputerze:",
            "enter_code": "Wpisz kod:",
            "waiting_sign_in": "TubeTV czeka na zakończenie logowania.",
            "smarttube_login_description": "TubeTV używa logowania urządzenia YouTube TV w stylu SmartTube, przechowuje token odświeżania w pęku kluczy i obsługuje konta marki.",
            "profile_active": "Aktywny profil YouTube",
            "profiles_found": "Znalezione profile YouTube",
            "sign_in_complete": "Logowanie zakończone.",
            "signed_out": "Konto YouTube zostało wylogowane.",
            "profile_error": "Profile",
            "subtitles_preferred_status": "Napisy",
            "no_playback_source": "Ten film nie ma jeszcze źródła możliwego do odtworzenia.",
            "adaptive_fallback": "Nie udało się połączyć wyższej jakości. Odtwarzana jest zgodna wersja.",
            "quality_change_error": "Zmiana jakości",
            "loading_languages": "Ładowanie dostępnych języków…",
            "auth_tv_page_unavailable": "Nie udało się wczytać YouTube TV.",
            "auth_client_script_not_found": "YouTube TV nie zwrócił skryptu logowania.",
            "auth_credentials_not_found": "Nie udało się ustalić aktualnych danych logowania YouTube TV.",
            "auth_invalid_response": "YouTube zwrócił nieprawidłową odpowiedź.",
            "auth_denied": "Logowanie zostało odrzucone.",
            "auth_expired": "Kod logowania wygasł.",
            "auth_not_signed_in": "Nie jesteś zalogowany w YouTube.",
            "auth_refresh_failed": "Nie udało się odświeżyć logowania do YouTube.",
            "caption_error_invalid_video": "Nieprawidłowy identyfikator filmu dla napisów.",
            "caption_error_invalid_response": "YouTube zwrócił nieprawidłową odpowiedź dla napisów.",
            "caption_error_not_found": "Ten film nie ma dostępnych napisów.",
            "caption_error_invalid_url": "Nie udało się utworzyć adresu URL napisów.",
            "caption_error_invalid_payload": "YouTube zwrócił napisy w nieznanym formacie.",
            "authenticated_player_not_signed_in": "Konto YouTube nie jest zalogowane.",
            "authenticated_player_invalid_response": "Zalogowany odtwarzacz YouTube zwrócił nieprawidłową odpowiedź.",
            "authenticated_player_unavailable": "Ten film nie jest dostępny dla tego konta.",
            "authenticated_player_no_stream": "Zalogowany odtwarzacz YouTube nie zwrócił strumienia zgodnego z Apple TV.",
            "youtube_request_invalid": "Nie udało się utworzyć żądania YouTube.",
            "youtube_response_invalid": "YouTube zwrócił nieprawidłową odpowiedź.",
            "youtube_page_data_missing": "Nie udało się wczytać danych YouTube. Struktura strony mogła się zmienić.",
            "unknown": "Nieznane",
            "invalid_video_id": "Nieprawidłowy identyfikator filmu YouTube.",
            "no_playable_stream": "Nie znaleziono strumienia zgodnego z Apple TV.",
            "youtube_network_blocked": "YouTube tymczasowo blokuje tę sieć. Wyłącz VPN, zmień serwer VPN lub spróbuj ponownie za kilka minut.",
            "youtube_sign_in_required": "Ten film ma ograniczenie wiekowe lub wymaga zalogowania."
        ],
        "sk": [
            "home": "Domov",
            "subscriptions": "Odbery",
            "channels": "Kanály",
            "history": "História",
            "playlists": "Playlisty",
            "save_to_playlist": "Uložiť do playlistu",
            "manage_playlists": "Vybrať playlisty",
            "loading_playlists": "Načítavam playlisty…",
            "create_playlist": "Vytvoriť",
            "new_playlist_name": "Názov nového playlistu",
            "search": "Hľadať",
            "settings": "Nastavenia",
            "youtube_no_channels": "YouTube nevrátil žiadne odoberané kanály.",
            "recommended": "Odporúčané",
            "more_videos": "Ďalšie videá",
            "videos": "Videá",
            "subscribe_channel": "Odoberať",
            "unsubscribe_channel": "Odoberané",
            "play": "Prehrať",
            "playing": "Prehrávanie",
            "like": "Páči sa mi",
            "dislike": "Nepáči sa mi",
            "quality": "Kvalita",
            "automatic": "Automaticky",
            "automatic_translation": "Automatický preklad",
            "audio": "Zvuk",
            "original_audio": "Originál",
            "captions": "Titulky",
            "captions_on": "Zapnuté",
            "captions_off": "Vypnuté",
            "speed": "Rýchlosť",
            "normal_speed": "Normálna",
            "search_placeholder": "Hľadať na YouTube alebo vložiť URL / ID videa",
            "play_pasted_video": "Prehrať vložené YouTube video",
            "playback_section": "Prehrávanie",
            "preferred_quality": "Preferovaná kvalita",
            "subtitles_section": "Titulky",
            "auto_enable_subtitles": "Automaticky zapnúť titulky",
            "auto_translate_subtitles": "Automaticky prekladať titulky",
            "preferred_subtitle_language": "Preferovaný jazyk titulkov",
            "language_section": "Jazyk",
            "app_language": "Jazyk aplikácie",
            "youtube_account": "YouTube účet",
            "signed_in": "Prihlásené k YouTube",
            "youtube_profile": "YouTube profil",
            "refresh_profiles": "Obnoviť profily",
            "sign_out": "Odhlásiť účet",
            "sign_in": "Prihlásiť YouTube účet",
            "loading_stream": "Hľadám stream…",
            "preparing_video": "Pripravujem video…",
            "switching_quality": "Mením kvalitu…",
            "loading_captions": "Načítavam titulky…",
            "captions_unavailable": "Titulky nie sú dostupné",
            "current_playback": "Aktuálne prehrávanie",
            "youtube_no_videos": "YouTube nevrátil žiadne videá.",
            "youtube_no_playlists": "YouTube nevrátil žiadne playlisty.",
            "playlist_empty": "Tento playlist neobsahuje žiadne dostupné videá.",
            "loading_playlist": "Načítavam playlist…",
            "loading_channel": "Načítavam kanál…",
            "channel_no_videos": "Tento kanál nevrátil žiadne dostupné videá.",
            "sign_in_hint": "Prihlás sa v Nastavenia → Účet.",
            "hdr_available": "HDR výstup je dostupný",
            "hdr_unavailable": "HDR výstup momentálne nie je dostupný",
            "ads_active": "Reklamy: blokovanie aktívne",
            "ads_description": "TubeTV neposiela reklamné umiestnenia YouTube do AVPlayera a uprednostňuje priame obsahové video/audio streamy.",
            "subtitle_fallback_description": "Keď preferovaná stopa titulkov nie je dostupná, TubeTV môže použiť dostupnú alebo automaticky generovanú stopu a preložiť ju.",
            "language_restart_note": "Jazyk rozhrania sa na podporovaných obrazovkách zmení okamžite.",
            "waiting_confirmation": "Čakám na potvrdenie…",
            "open_on_phone": "Na telefóne alebo počítači otvor:",
            "enter_code": "Zadaj kód:",
            "waiting_sign_in": "TubeTV čaká na dokončenie prihlásenia.",
            "smarttube_login_description": "TubeTV používa prihlásenie zariadenia YouTube TV v štýle SmartTube, ukladá obnovovací token do Keychainu a podporuje Brand účty.",
            "profile_active": "Aktívny YouTube profil",
            "profiles_found": "Nájdené YouTube profily",
            "sign_in_complete": "Prihlásenie bolo dokončené.",
            "signed_out": "YouTube účet bol odhlásený.",
            "profile_error": "Profily",
            "subtitles_preferred_status": "Titulky",
            "no_playback_source": "Toto video zatiaľ nemá prehrateľný zdroj.",
            "adaptive_fallback": "Vyššiu kvalitu sa nepodarilo spojiť. Prehráva sa kompatibilná verzia.",
            "quality_change_error": "Zmena kvality",
            "loading_languages": "Načítavam dostupné jazyky…",
            "auth_tv_page_unavailable": "Nepodarilo sa načítať YouTube TV.",
            "auth_client_script_not_found": "YouTube TV nevrátil prihlasovací skript.",
            "auth_credentials_not_found": "Nepodarilo sa zistiť aktuálne prihlasovacie údaje YouTube TV.",
            "auth_invalid_response": "YouTube vrátil neplatnú odpoveď.",
            "auth_denied": "Prihlásenie bolo zamietnuté.",
            "auth_expired": "Prihlasovací kód vypršal.",
            "auth_not_signed_in": "Nie si prihlásený k YouTube.",
            "auth_refresh_failed": "Obnovenie prihlásenia k YouTube zlyhalo.",
            "caption_error_invalid_video": "Neplatné ID videa pre titulky.",
            "caption_error_invalid_response": "YouTube vrátil neplatnú odpoveď pre titulky.",
            "caption_error_not_found": "Toto video nemá dostupné titulky.",
            "caption_error_invalid_url": "Nepodarilo sa vytvoriť adresu titulkov.",
            "caption_error_invalid_payload": "YouTube vrátil titulky v neznámom formáte.",
            "authenticated_player_not_signed_in": "YouTube účet nie je prihlásený.",
            "authenticated_player_invalid_response": "Prihlásený YouTube prehrávač vrátil neplatnú odpoveď.",
            "authenticated_player_unavailable": "Toto video nie je pre tento účet dostupné.",
            "authenticated_player_no_stream": "Prihlásený YouTube prehrávač nevrátil stream kompatibilný s Apple TV.",
            "youtube_request_invalid": "Nepodarilo sa vytvoriť požiadavku na YouTube.",
            "youtube_response_invalid": "YouTube vrátil neplatnú odpoveď.",
            "youtube_page_data_missing": "Nepodarilo sa načítať dáta YouTube. Štruktúra stránky sa mohla zmeniť.",
            "unknown": "Neznáme",
            "invalid_video_id": "Neplatné ID videa YouTube.",
            "no_playable_stream": "Pre toto video sa nenašiel stream kompatibilný s Apple TV.",
            "youtube_network_blocked": "YouTube túto sieť dočasne blokuje. Vypni VPN, skús iný VPN server alebo počkaj niekoľko minút a skús to znova.",
            "youtube_sign_in_required": "Toto video je vekovo obmedzené alebo vyžaduje prihlásenie."
        ]
    ]
}
